#ifndef CLOUD_SPEAKER_CFG_H_
#define CLOUD_SPEAKER_CFG_H_

#include "cloud_asr_cfg.h"

#ifndef CLOUD_SPEAKER_SERVER_IP
#define CLOUD_SPEAKER_SERVER_IP CLOUD_SERVER_IP
#endif

#ifndef CLOUD_SPEAKER_SERVER_PORT
#define CLOUD_SPEAKER_SERVER_PORT CLOUD_SERVER_PORT
#endif

#ifndef CLOUD_SPEAKER_LOCAL_PORT
#define CLOUD_SPEAKER_LOCAL_PORT CLOUD_SERVER_LOCAL_PORT
#endif

#ifndef CLOUD_SPEAKER_DEFAULT_ID
#define CLOUD_SPEAKER_DEFAULT_ID "speaker1"
#endif

#ifndef CLOUD_SPEAKER_ENROLL_REQUIRED
#define CLOUD_SPEAKER_ENROLL_REQUIRED (3U)
#endif

#ifndef CLOUD_SPEAKER_RESULT_TIMEOUT_MS
#define CLOUD_SPEAKER_RESULT_TIMEOUT_MS CLOUD_RESULT_TIMEOUT_MS
#endif

#endif
