"""
P2 mel filterbank 生成器 / 验证工具
====================================
与 train_model.py 使用完全相同的参数（fmax=7600）生成 mel_filterbank.h，
保证 MCU 端特征提取与 PC 端训练预处理完全对齐。

使用方法:
    python tools/gen_mel_filterbank.py [--verify]

    --verify   仅验证当前 mel_filterbank.h 与重新计算结果的最大差距，不写文件。
               不加此参数则直接覆盖写入 src/mel_filterbank.h。
"""

import argparse
import sys
from pathlib import Path

import numpy as np

# ──────────────────────────────────────────────
# 参数必须与 train_model.py 完全一致
# ──────────────────────────────────────────────
SAMPLE_RATE  = 16000
N_FFT        = 1024
N_MELS       = 40
FMAX         = min(7600, SAMPLE_RATE // 2)   # = 7600
MEL_BINS     = N_FFT // 2 + 1               # = 513


def _hz_to_mel(freq: np.ndarray) -> np.ndarray:
    return 2595.0 * np.log10(1.0 + freq / 700.0)


def _mel_to_hz(mel: np.ndarray) -> np.ndarray:
    return 700.0 * (10 ** (mel / 2595.0) - 1.0)


def build_filterbank() -> np.ndarray:
    """返回 shape=(N_MELS, MEL_BINS) float32 mel 滤波器矩阵"""
    freqs = np.linspace(0, SAMPLE_RATE / 2, MEL_BINS)  # linspace(0, 8000, 513)

    mel_min = _hz_to_mel(np.array([20.0]))[0]
    mel_max = _hz_to_mel(np.array([float(FMAX)]))[0]

    mel_points = np.linspace(mel_min, mel_max, N_MELS + 2)
    hz_points  = _mel_to_hz(mel_points)

    fb = np.zeros((N_MELS, MEL_BINS), dtype=np.float32)
    for m in range(1, N_MELS + 1):
        left, center, right = hz_points[m - 1], hz_points[m], hz_points[m + 1]

        # 上升沿 [left, center]
        li = np.where((freqs >= left) & (freqs <= center))[0]
        if li.size > 0:
            fb[m - 1, li] = (freqs[li] - left) / max(center - left, 1e-8)

        # 下降沿 [center, right]
        ri = np.where((freqs >= center) & (freqs <= right))[0]
        if ri.size > 0:
            fb[m - 1, ri] = (right - freqs[ri]) / max(right - center, 1e-8)

    return fb


def write_header(fb: np.ndarray, out_path: Path) -> None:
    lines = []
    lines.append("/* AUTO-GENERATED by tools/gen_mel_filterbank.py  —  DO NOT EDIT MANUALLY  */")
    lines.append("/* Parameters: SR=%d  N_FFT=%d  N_MELS=%d  fmax=%d  MEL_BINS=%d           */" %
                 (SAMPLE_RATE, N_FFT, N_MELS, FMAX, MEL_BINS))
    lines.append("#ifndef MEL_FILTERBANK_H_")
    lines.append("#define MEL_FILTERBANK_H_")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define MEL_N_MELS %d" % N_MELS)
    lines.append("#define MEL_N_FFT  %d" % N_FFT)
    lines.append("#define MEL_BINS   (%d)" % MEL_BINS)
    lines.append("")
    lines.append("static const float g_mel_filterbank[MEL_N_MELS][MEL_BINS] = {")

    for m in range(N_MELS):
        row_vals = ", ".join("%.8ef" % v for v in fb[m])
        comma = "," if m < N_MELS - 1 else ""
        lines.append("    {%s}%s" % (row_vals, comma))

    lines.append("};")
    lines.append("")
    lines.append("#endif // MEL_FILTERBANK_H_")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print("Wrote  %s  (%d mel filters × %d bins, fmax=%d Hz)" %
          (out_path, N_MELS, MEL_BINS, FMAX))


def verify_existing(fb_new: np.ndarray, header_path: Path) -> bool:
    """
    从现有 .h 文件解析已有滤波器权重并与重新计算的进行比较。
    返回 True 表示匹配（最大绝对差 < 1e-5）。
    """
    text = header_path.read_text(encoding="utf-8")
    import re
    # 匹配形如 "    {val, val, ...}," 或 "    {val, val, ...}" 的行（每行一个 mel filter）
    rows_raw = re.findall(r'^\s*\{([^{}]+)\}', text, re.MULTILINE)

    rows = [r for r in rows_raw if r.count(',') == MEL_BINS - 1]

    if len(rows) != N_MELS:
        print("WARN: 解析到 %d 行，期望 %d，跳过比较" % (len(rows), N_MELS))
        return False

    fb_existing = np.zeros((N_MELS, MEL_BINS), dtype=np.float32)
    for m, row in enumerate(rows):
        vals = [float(v.strip().rstrip('f')) for v in row.split(',')]
        fb_existing[m] = np.array(vals, dtype=np.float32)

    max_diff = float(np.max(np.abs(fb_new - fb_existing)))
    print("最大绝对差 (existing vs regenerated): %.2e" % max_diff)

    if max_diff < 1e-5:
        print("✅  mel_filterbank.h 与训练参数完全一致 (fmax=%d)" % FMAX)
        return True
    else:
        print("❌  mel_filterbank.h 与训练参数不一致，建议重新生成！")
        return False


def main():
    parser = argparse.ArgumentParser(description="生成/验证 mel_filterbank.h")
    parser.add_argument("--verify", action="store_true",
                        help="仅验证不覆盖写入")
    args = parser.parse_args()

    repo_root  = Path(__file__).resolve().parent.parent
    out_path   = repo_root / "src" / "mel_filterbank.h"

    fb = build_filterbank()
    print("Mel filterbank params: SR=%d  N_FFT=%d  N_MELS=%d  fmax=%d" %
          (SAMPLE_RATE, N_FFT, N_MELS, FMAX))

    if args.verify:
        if out_path.exists():
            verify_existing(fb, out_path)
        else:
            print("未找到现有 mel_filterbank.h，无法比较。")
        return

    # 如果文件已存在，先验证
    if out_path.exists():
        same = verify_existing(fb, out_path)
        if same:
            print("文件内容相同，无需覆盖。")
            return

    write_header(fb, out_path)


if __name__ == "__main__":
    main()
